### ISSUE TITLE
Image Rios

### ISSUE THREAD

**Issue by 1crazyshadow** [Staley-Robotics/StaleyRC2020#1]
Follow these steps and make sure all Roborios we have are imaged with the latest

https://docs.wpilib.org/en/latest/docs/getting-started/getting-started-frc-control-system/imaging-your-roborio.html

**Comment by SHS-Programmers** [comment]
4 rios updated to 2020 image with Phoenix libraries

**Comment by Dustin-Klein** [comment]
Ethan did the bad.  Now we only have one currently setup to work properly.  We need to do the other 3.  This is not an urgent issue, but it needs to get done.

**Comment by Dustin-Klein** [comment]
Supposedly Ethan did this correct this time
