### ISSUE TITLE
Create Shooter subsystem and commands

### ISSUE THREAD

**Issue by Dustin-Klein** [Staley-Robotics/StaleyRC2020#24]
This relies heavily on #11 so it would be best to wait until that issue is resolved.

See Structure.md for more info about the shooter.

**Comment by SHS-Programmers** [comment]
Code written. Not tested. Needs testing to write calculateAngularVelocity method.

**Comment by Dustin-Klein** [comment]
Code implemented in #32

**Comment by Dustin-Klein** [comment]
Shooter bad
