### ISSUE TITLE
Remove Unnecessary ZeroEncoder Command Classes

### ISSUE THREAD

**Issue by 1crazyshadow** [Staley-Robotics/StaleyRC2020#40]
There are currently two ZeroEncoder Command Classes. One is in the commands package, the other is a layer deeper in the commands.drivetrain package

Make sure they aren't being used anywhere and remove them. Instead of using these, use instant commands to call the zeroEncoder method in DriveTrain.

**Comment by SHS-Programmers** [comment]
Deleted.
