### ISSUE TITLE
Exception Handling For Objects in DriveTrain Class

### ISSUE THREAD

**Issue by 1crazyshadow** [Staley-Robotics/StaleyRC2020#41]
There are several objects in the DriveTrain class such as the TalonSRX's and the NavX gyro that currently have no exception handling. Add in exception handling for constructing these so that the Driver Station will be sent messages if any of the devices are not connected / sending signals to the roborio. 

Examples of how to do this exception handling can be found in the 2018 DriveTrain code.

**Comment by AkashaSnow** [comment]
Resolved in merge with fuvk
