### ISSUE TITLE
Store Deadzones In Value For Rotation

### ISSUE THREAD

**Issue by 1crazyshadow** [Staley-Robotics/StaleyRC2020#46]
In The worldOfTanksDrive method in DriveTrain, there is a deadzone check for if the joysticks are in the deadzone, store this deadzone value in a single value.

**Comment by Dustin-Klein** [comment]
Maybe we could even create an implementation of XboxController with build in deadzones?

**Comment by AkashaSnow** [comment]
Resolved in merge with fuvk
