### ISSUE TITLE
Bind controller buttons

### ISSUE THREAD

**Issue by SHS-Programmers** [Staley-Robotics/StaleyRC2020#49]
Bind controller buttons to robot actions.

**Comment by BEF-BEF** [comment]
**alternate controller**
a whilehealld or something
run intake, run magazine (same time)
b toggle(for ball. this one has to be b)
vision aligns, run magazine backward for like 0.00000001 seconds. retract piston hardstop. run magazine if flywheel speed is at threshold.
c button toggle or soemthing
lower/raise intake
up on dpad
make wof guy go up
right on dpad
make wof guy do color
left on dpad
make wof guy do position
down on dpad
make wof guy go down
mast/winch

**drive**
drive rightstick y axis
mast go up (variable power positive or negative)
winch extend (same variable power)
right trigger
go forward (variable power)
left trigger
go not forward (variable power)
drive leftstick x axis
crotate
x button
shift (high/low toggle)
b (for bvision align)
vision align

**Comment by Dustin-Klein** [comment]
finished
