### ISSUE TITLE
Generate new project

### ISSUE THREAD

**Issue by 1crazyshadow** [Staley-Robotics/StaleyRC2020#5]

**Comment by Dustin-Klein** [comment]
Since we are not using Visual Studio Code, you will need to use this tool to generate the project:
https://github.com/wpilibsuite/vscode-wpilib/releases

We want to use the new Command Based template

**Comment by SHS-Programmers** [comment]
New project generated and dependencies set up.

**Comment by Dustin-Klein** [comment]
@bobtheragelot We missed a couple folders on the .gitignore file 

 - /.idea
 - /.vscode

so we will need to add those

**Comment by SHS-Programmers** [comment]
Cancel that

**Comment by Dustin-Klein** [comment]
Changes made.  This is finished
