### ISSUE TITLE
Create GitHub work flow

### ISSUE THREAD

**Issue by 1crazyshadow** [Staley-Robotics/StaleyRC2020#7]

**Comment by Dustin-Klein** [comment]
Tutorial here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#creating-a-workflow-file

We are also probably going to want to just use the gradle template.

The steps I expect we will need in the workflow are:
1. build the code
2. run the tests
3. validate the code
     - checkstyle
     - maybe spotbugs

and if all that goes good your code is good enough to be merged into master, after a review of course.

**Comment by Dustin-Klein** [comment]
Done for now.

Workflow file can be found at .github/worflows/main.yml

We could go back in the future and add spotbugs, but for now this is fine.
