### ISSUE TITLE
Make autonomous steps run parallel where needed

### ISSUE THREAD

**Issue by SHS-Programmers** [Staley-Robotics/StaleyRC2020#75]
Right now all of our autos are strictly sequential.  Some of our actions will need to be done in parallel so we need to figure out how to do that and implement it.

**Comment by Dustin-Klein** [comment]
You make a ParallelCommand group object and just treat that as one step in the process.

Example:
```
addCommands(
  new DriveToGoal(m_drive),
   new ParallelCommandGroup(
      new RaiseElevator(m_elevator),
      new SetWristPosition(m_wrist)),
   new ScoreTube(m_wrist));
)
```

**Comment by Dustin-Klein** [comment]
This was created but was abandoned at competition due to lack of testing time.
